### ISSUE TITLE
Predicate boolean logic

### ISSUE THREAD

**Issue by adriangb** [annotated-types/annotated-types#47]
#45 adds basic negation for predicates. Would it make sense to also add `Or`? `And` is already implicitly possible by putting multiple predicates in a single `Annotated`.

**Comment by Zac-HD** [comment]
`Or` is already possible via `Union[...]`, though potentially pretty awkward to express in full.

I'd prefer to keep things simple and let people write out the long forms, or use `Predicate` to express it concisely in code if they prefer.  There's a real value in keeping `annotated-types` as small and simple as possible, since that makes it much easier to add support to new libraries, easier for users to learn, and keeps options open about possibly upstreaming it someday.

**Comment by adriangb** [comment]
Okay, good points, I'll close this for now
