### ISSUE TITLE
Suggestion: Unique or some other name to check for uniqueness?

### ISSUE THREAD

**Issue by ManiMozaffar** [annotated-types/annotated-types#51]
I want to check if inside a list, there's 3 different types of string, so:

```python 
lst = ["a", "b", "c", "c"]
```

so I can write
```python
Three_Occurrence = Annotated[str, Unique(3)]
```

Which would be great if pydantic also serves that (I'm mainly asking it for pydantic haha)

Could be really useful inside fastapi, where we want all enums to be presented, or some does. We can write validator ofc, but i think this would be useful.

**Comment by Zac-HD** [comment]
I think what you're asking for is `MinDistinct(3)`, in that it accepts any collection with at least n distinct elements.  There's also the complementary `MaxDistinct(5)` which might be lower than the `MaxLen` or even `MinLen`.

However, this seems rare enough to me that I'd suggest using `Predicate` for now - adding new interfaces before we have _really_ solid evidence that they'll be widely useful is very expensive, because we want many downstream libraries to support the whole `annotated-types` API.

----------

If we _did_ decide to support a `Unique` metadatum, I'd want it to look like `Unique(by=None)` in order to support [Hypothesis' `unique=True`, `unique_by=fn`, and `unique_by=(fn1, fn2)` arguments](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.lists); hence my renaming above.
