### ISSUE TITLE
Add annotation for `repr`

### ISSUE THREAD

**Issue by JacobHayes** [annotated-types/annotated-types#72]
I'd like to control whether a field should be included in the `repr` of a model/dataclass/etc, similar to `pydantic.Field(repr=...)`. Aside from `doc()`, it seems like the other annotated types are more validation oriented, so perhaps it's a slippery slope to start adding other metadata fields. If interested in adding, I'd be happy try adding here and `pydantic`.

**Comment by tiangolo** [comment]
Hello! PEP 727 was withdrawn (I'm the author 😅).

Given that, I would imagine you would prefer to remove `doc()` from here, I'm writing here just to note that it would be fine by me. ☕ 

I would let you all (@adriangb, @samuelcolvin, @Zac-HD, and others) decide on that, but it would be fine by me.

---

Some extra context:

`Doc` was added to `typing_extensions` because of PEP 727, then, after receiving quite some pushback, I agreed to withdraw it. It was taking me a long time to get back to it, so Jelle helped me handle the withdrawal PR update.

The conclusion of that PEP was that it was better to do all that as a third-party package first, a bit more constrained to FastAPI (and/or any other interested package), so now I just published https://github.com/fastapi/annotated-doc to keep that in a smaller and more constrained scope.

FastAPI is already migrated to use it, and https://github.com/mkdocstrings/griffe-typingdoc already supports this new package, so the FastAPI reference docs are unchanged.

My packages don't depend on `annotated_types.doc`, I suspect no one else would be using it, so it's probably safe to (deprecate and?) remove.
