### ISSUE TITLE
Add containment constraints

### ISSUE THREAD

**Issue by adriangb** [annotated-types/annotated-types#75]
I'd like to poll appetite for adding something like:

```python
import annotated_types as at

CountryCode = Annotated[str, at.In({"+1", "+54", "+39"})]
```

**Comment by adriangb** [comment]
cc @Zac-HD

**Comment by Zac-HD** [comment]
```python
from typing import Literal

CountryCode = Literal["+1", "+54", "+39"]
```

But OK, suppose that we wanted to do this for things that can't be represented in a `Literal`, however common or rare that is.  Quick thoughts:
- https://github.com/HypothesisWorks/hypothesis/issues/3795 _does_ explicitly contemplate handling some simple cases in Hypothesis
- we can't reasonably support mutable elements
- we need some way to check whether the elements are instances of the annotated type, which we can only do in simple cases because a full runtime typechecker is well out of scope for Hypothesis.
- we need to have a consistent ordering of the elements, which means either a sequence or a collection where the (allowed) elements are sortable.

Given all the constraints, I'm somewhat dubious that this would be worth the trouble.

**Comment by adriangb** [comment]
Even if hypothesis can’t support this very well, there’s still value for other tools: Pydantic can convert the container into a Rust set and do the fast comparison in Rust. But I admit this only makes sense if it’s a common thing to do _and_ if Literal doesn’t cover these use cases.

**Comment by Zac-HD** [comment]
I'm inclined to close the issue until/unless someone comes up with two or three cases that `Literal` doesn't cover but Pydantic could if we added this feature.
